import {
  GENSHIN_IMPACT_GOLD_TRIM,
  GENSHIN_IMPACT_LANTERN,
} from './asset-urls.ts'

export const GENSHIN_IMPACT_CHIBI = GENSHIN_IMPACT_LANTERN
export const GENSHIN_IMPACT_BRAND = GENSHIN_IMPACT_LANTERN
export const GENSHIN_IMPACT_BOW_CLEAN = GENSHIN_IMPACT_GOLD_TRIM
export const GENSHIN_IMPACT_NEW_SESSION = GENSHIN_IMPACT_LANTERN
export const GENSHIN_IMPACT_SIDEBAR_SWAG = GENSHIN_IMPACT_GOLD_TRIM
export const GENSHIN_IMPACT_TOP_TRIM_TILE = GENSHIN_IMPACT_GOLD_TRIM
