import {
  GENSHIN_IMPACT_DAWN,
  GENSHIN_IMPACT_NIGHT,
  GENSHIN_IMPACT_TRAVELER,
} from './asset-urls.ts'

export const GENSHIN_IMPACT_PALACE_LIGHT = GENSHIN_IMPACT_DAWN
export const GENSHIN_IMPACT_PALACE_DARK = GENSHIN_IMPACT_NIGHT
export const GENSHIN_IMPACT_TRAVELER_LEFT = GENSHIN_IMPACT_TRAVELER
export const GENSHIN_IMPACT_TRAVELER_RIGHT = GENSHIN_IMPACT_TRAVELER
