import {
  GENSHIN_IMPACT_DAWN,
  GENSHIN_IMPACT_NIGHT,
} from './asset-urls.ts'

export const GENSHIN_BOOT_ERROR_LEFT = GENSHIN_IMPACT_DAWN
export const GENSHIN_BOOT_ERROR_RIGHT = GENSHIN_IMPACT_NIGHT
