import {
  GENSHIN_IMPACT_GOLD_FRAME,
  GENSHIN_IMPACT_GOLD_TRIM,
} from './asset-urls.ts'

export const GENSHIN_IMPACT_BOTTOM_TRIM_TILE = GENSHIN_IMPACT_GOLD_TRIM
export const GENSHIN_IMPACT_BOTTOM_CREST = GENSHIN_IMPACT_GOLD_FRAME
export const GENSHIN_IMPACT_SIDEBAR_CORNER = GENSHIN_IMPACT_GOLD_FRAME
export const GENSHIN_IMPACT_COMPOSER_FRAME = GENSHIN_IMPACT_GOLD_FRAME
export const GENSHIN_IMPACT_SETTINGS_FRAME = GENSHIN_IMPACT_GOLD_FRAME
