import {
  GENSHIN_IMPACT_GOLD_FRAME,
  GENSHIN_IMPACT_GOLD_TRIM,
} from './asset-urls.ts'

export const GENSHIN_IMPACT_COMPOSER_FRAME_SHELL = GENSHIN_IMPACT_GOLD_FRAME
export const GENSHIN_IMPACT_COMPOSER_RIBBON_LEFT_CAP = GENSHIN_IMPACT_GOLD_TRIM
export const GENSHIN_IMPACT_COMPOSER_RIBBON_LEFT_FILL = GENSHIN_IMPACT_GOLD_TRIM
export const GENSHIN_IMPACT_COMPOSER_RIBBON_RIGHT_FILL = GENSHIN_IMPACT_GOLD_TRIM
export const GENSHIN_IMPACT_COMPOSER_RIBBON_RIGHT_CAP = GENSHIN_IMPACT_GOLD_TRIM
export const GENSHIN_IMPACT_COMPOSER_LACE_TILE = GENSHIN_IMPACT_GOLD_TRIM
