import { GENSHIN_IMPACT_LANTERN } from './asset-urls.ts'

export const SLEEPY_32 = GENSHIN_IMPACT_LANTERN
export const DELIGHTED_32 = GENSHIN_IMPACT_LANTERN
export const DELIGHTED_192 = GENSHIN_IMPACT_LANTERN
export const DELIGHTED_512 = GENSHIN_IMPACT_LANTERN
export const DETERMINED_32 = GENSHIN_IMPACT_LANTERN
