import {
  GENSHIN_IMPACT_GOLD_FRAME,
  GENSHIN_IMPACT_GOLD_TRIM,
} from './asset-urls.ts'

export const GENSHIN_IMPACT_WORKSPACE_SHIELD = GENSHIN_IMPACT_GOLD_FRAME
export const GENSHIN_IMPACT_WORKSPACE_RIBBON = GENSHIN_IMPACT_GOLD_TRIM
